name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  setup-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm

  build-and-deploy-demo:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies (demo)
        run: pnpm install
        working-directory: ./demo
      - name: Build demo project
        run: pnpm run build
        working-directory: ./demo
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/build
          destination_dir: demo

  build-and-deploy-docs:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies (docs)
        run: pnpm install
        working-directory: ./docs
      - name: Build docs project
        run: pnpm run build
        working-directory: ./docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          destination_dir: docs